wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1680965248.574557
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 23
      4: 3.9.16
      5: 0.13.4
      8:
      - 1
      - 5
